name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Run command '...'
        2. See error
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: prompt-smith version
      placeholder: "2.5.2"
    validations:
      required: true

  - type: dropdown
    id: command
    attributes:
      label: Command
      description: Which command were you using?
      options:
        - /ps:r (Review)
        - /ps:a (Intercept)
        - /ps:lint (LINT)
        - /ps:build (BUILD)
        - /ps:help (Help)
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
