name: Question
description: Ask a question about prompt-smith
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask your question below.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant context or what you've already tried

  - type: dropdown
    id: topic
    attributes:
      label: Topic
      description: What is this question about?
      options:
        - Installation
        - Usage
        - Configuration
        - Contributing
        - Other
    validations:
      required: true
